In [24]:
import numpy as np
from scipy import stats

In [25]:
test = np.array([1, 2, 3, 4, 5])
print(test)
print(type(test))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [26]:
test2 = np.random.randint(1, 100, 50)
print(test2)

[38 69 13 57 46 27 37 50 17 90 24 80 14 48 93 67 35 60  2 62 41 26 84 96
 79 23 24 62 80 63 50 76  3 37 77 66 91 14 78 29 92  3 95  5 58 23 82 72
 26 12]


In [27]:
print(np.sort(test2))

[ 2  3  3  5 12 13 14 14 17 23 23 24 24 26 26 27 29 35 37 37 38 41 46 48
 50 50 57 58 60 62 62 63 66 67 69 72 76 77 78 79 80 80 82 84 90 91 92 93
 95 96]


In [28]:
filter_odd = []
filter_even = []

for element in test2:
    if element % 2 != 0:
        filter_odd.append(element)
    else:
        filter_even.append(element)

print(filter_odd)
print(filter_even)

[69, 13, 57, 27, 37, 17, 93, 67, 35, 41, 79, 23, 63, 3, 37, 77, 91, 29, 3, 95, 5, 23]
[38, 46, 50, 90, 24, 80, 14, 48, 60, 2, 62, 26, 84, 96, 24, 62, 80, 50, 76, 66, 14, 78, 92, 58, 82, 72, 26, 12]


In [29]:
test3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(test3)

[1 2 3 4 5 6 7 8 9]


In [30]:
print(test3.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
test4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(test4)

[[1 2 3 4]
 [5 6 7 8]]


In [32]:
print(test4.reshape(-1))

[1 2 3 4 5 6 7 8]


In [35]:
print(test2)

[38 69 13 57 46 27 37 50 17 90 24 80 14 48 93 67 35 60  2 62 41 26 84 96
 79 23 24 62 80 63 50 76  3 37 77 66 91 14 78 29 92  3 95  5 58 23 82 72
 26 12]


In [34]:
testmean = np.mean(test2)
testmedian = np.median(test2)
testmode = stats.mode(test2)

print(testmean, testmedian, testmode)

49.92 50.0 ModeResult(mode=3, count=2)


In [36]:
testdev = np.std(test2)
print(testdev)
# standart deviation

28.665547264966


In [37]:
testperc = np.percentile(test2, 75)
print(testperc)

76.75
