In [1]:
import numpy as np
from scipy import stats

In [25]:
test = np.array([1, 2, 3, 4, 5])
print(test)
print(type(test))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [26]:
test2 = np.random.randint(1, 100, 50)
print(test2)

[38 69 13 57 46 27 37 50 17 90 24 80 14 48 93 67 35 60  2 62 41 26 84 96
 79 23 24 62 80 63 50 76  3 37 77 66 91 14 78 29 92  3 95  5 58 23 82 72
 26 12]


In [27]:
print(np.sort(test2))

[ 2  3  3  5 12 13 14 14 17 23 23 24 24 26 26 27 29 35 37 37 38 41 46 48
 50 50 57 58 60 62 62 63 66 67 69 72 76 77 78 79 80 80 82 84 90 91 92 93
 95 96]


In [28]:
filter_odd = []
filter_even = []

for element in test2:
    if element % 2 != 0:
        filter_odd.append(element)
    else:
        filter_even.append(element)

print(filter_odd)
print(filter_even)

[69, 13, 57, 27, 37, 17, 93, 67, 35, 41, 79, 23, 63, 3, 37, 77, 91, 29, 3, 95, 5, 23]
[38, 46, 50, 90, 24, 80, 14, 48, 60, 2, 62, 26, 84, 96, 24, 62, 80, 50, 76, 66, 14, 78, 92, 58, 82, 72, 26, 12]


In [29]:
test3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(test3)

[1 2 3 4 5 6 7 8 9]


In [30]:
print(test3.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
test4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(test4)

[[1 2 3 4]
 [5 6 7 8]]


In [32]:
print(test4.reshape(-1))

[1 2 3 4 5 6 7 8]


In [35]:
print(test2)

[38 69 13 57 46 27 37 50 17 90 24 80 14 48 93 67 35 60  2 62 41 26 84 96
 79 23 24 62 80 63 50 76  3 37 77 66 91 14 78 29 92  3 95  5 58 23 82 72
 26 12]


In [34]:
testmean = np.mean(test2)
testmedian = np.median(test2)
testmode = stats.mode(test2)

print(testmean, testmedian, testmode)

49.92 50.0 ModeResult(mode=3, count=2)


In [36]:
testdev = np.std(test2)
print(testdev)
# standart deviation

28.665547264966


In [37]:
testperc = np.percentile(test2, 75)
print(testperc)

76.75


# machinelearningplus - 101 NumPy Exercises for Data Analysis (Python)

In [3]:
# Import numpy as np and print the version number

import numpy as np
print(np.__version__)

1.25.2


In [8]:
# Create a 1D array of numbers from 0 to 9

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Create a 3×3 numpy array of all True’s

true_array = np.full((3, 3), True)
true_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
# Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

# odd_arr = np.where(arr % 2)
# odd_arr

array([1, 3, 5, 7, 9])

In [24]:
# Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1] = -1
arr

# odd_arr = np.where(arr % 2 != 0)
# arr[odd_arr] = -1
# arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [32]:
# Replace all odd numbers in arr with -1 without changing arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

new_arr = np.where(arr % 2 == 1, -1, arr)

# arr
new_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [40]:
# Convert a 1D array to a 2D array with 2 rows

# np.arange(10).reshape(2, 5)
np.arange(10).reshape(2, -1)

# arr = np.arange(10)
# arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
# Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# np.stack((a, b))

# np.concatenate([a, b], axis=0)

np.vstack([a, b])

# np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
# Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a, b])

# np.concatenate([a, b], axis=1)

# np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [73]:
a = np.array([1,2,3])
# np.repeat(a, 3)
# np.tile(a, 3)

np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [75]:
#  Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [81]:
# From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [88]:
# Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# np.in1d(a, b)
# np.isin(a, b)

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [112]:
# Get all items between 5 and 10 from a

a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
# index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]

# a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])